In [3]:
import numpy as np

In [4]:
a= np.array([100,101,102,103])
a

array([100, 101, 102, 103])

In [10]:
b= np.array([[0,1],[3,9]])
b.shape
b.ndim

2

In [11]:
b[0,1]

1

In [1]:
b = np.array([[[1,2,3,4],[3,4,5,6],[1,0,5,8]],[[1,6,0,3,],[5,2,9,4],[9,5,7,3]]])
b.ndim

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
b = np.array([[[1,2,3,4],[3,4,5,6],[1,0,5,8]],[[1,6,0,3,],[5,2,9,4],[9,5,7,3]]])
b.ndim

3

In [4]:
b[0,1,0]

3

In [5]:
b[1,0,0]

1

In [6]:
b[2,0,0]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [1]:
import numpy as np


In [10]:
a= np.array([[1,2],[3,3],[4,5]])
a.shape
print(a)



[[1 2]
 [3 3]
 [4 5]]


In [15]:
b = [0,1]

print(b)

[0, 1]


In [16]:
b = np.array([[[1,2,3,4],[3,4,5,6],[1,0,5,8]],[[1,6,0,3,],[5,2,9,4],[9,5,7,3]]])
print(b)

[[[1 2 3 4]
  [3 4 5 6]
  [1 0 5 8]]

 [[1 6 0 3]
  [5 2 9 4]
  [9 5 7 3]]]


In [17]:
b[1,0,0]

1

In [18]:
b[1,1] = 10 
b

array([[[ 1,  2,  3,  4],
        [ 3,  4,  5,  6],
        [ 1,  0,  5,  8]],

       [[ 1,  6,  0,  3],
        [10, 10, 10, 10],
        [ 9,  5,  7,  3]]])

In [19]:
b

array([[[ 1,  2,  3,  4],
        [ 3,  4,  5,  6],
        [ 1,  0,  5,  8]],

       [[ 1,  6,  0,  3],
        [10, 10, 10, 10],
        [ 9,  5,  7,  3]]])

In [24]:
b = np.array([[[1,2],[1,3]],[[5,6],[9,8]],[[5,6],[9,8]]])
print(b)
b.ndim

[[[1 2]
  [1 3]]

 [[5 6]
  [9 8]]

 [[5 6]
  [9 8]]]


3

In [28]:
b[0,0]=10
b

array([[[10, 10],
        [10, 10]],

       [[ 5,  6],
        [ 9,  8]],

       [[ 5,  6],
        [ 9,  8]]])

In [35]:
np.array([0,4,-4], dtype=float)

array([ 0.,  4., -4.])

In [31]:
np.empty((2,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [2.11396107e-307, 6.23037317e-307, 2.22526399e-307]])

In [33]:
a = np.empty((2,3))
print(a)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [2.11396107e-307 6.23037317e-307 2.22526399e-307]]


In [80]:
z = np.empty((2,3))
np.set_printoptions(suppress = True)
print(z)

[[ 2.  4.  4.]
 [ 8.  6. 12.]]


In [40]:
x = np.zeros((4,2,3))
x

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [43]:
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.arange?

In [46]:
list(range(7))

[0, 1, 2, 3, 4, 5, 6]

In [47]:
list(range(3,7))

[3, 4, 5, 6]

In [49]:
np.arange(7.7,10,0.3)

array([7.7, 8. , 8.3, 8.6, 8.9, 9.2, 9.5, 9.8])

In [51]:
np.linspace?

In [52]:
np.linspace(10,30,5)

array([10., 15., 20., 25., 30.])

In [57]:
np.linspace(1,10,20).reshape(5,4)

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105,  3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789,  5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474,  7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [58]:
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [61]:
np.linspace(10,20,10, retstep=True)

(array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
        15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ]),
 1.1111111111111112)

In [62]:
np.linspace(10,20,10, endpoint=False)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [4]:
def f(i,j):
    return 2*i*j
np.fromfunction(f,(4,3))

In [5]:
import numpy as np

In [6]:
def f(i,j):
    return 2*i*j
np.fromfunction(f,(4,3))

array([[ 0.,  0.,  0.],
       [ 0.,  2.,  4.],
       [ 0.,  4.,  8.],
       [ 0.,  6., 12.]])

In [7]:
def f(i,j):
    return 5*i*j
np.fromfunction(f,(3,3))


array([[ 0.,  0.,  0.],
       [ 0.,  5., 10.],
       [ 0., 10., 20.]])

In [ ]:
# by using def f() we can create a new function

In [8]:
np.fromfunction(lambda i,j: 10*i*j,(4,4))  

array([[ 0.,  0.,  0.,  0.],
       [ 0., 10., 20., 30.],
       [ 0., 20., 40., 60.],
       [ 0., 30., 60., 90.]])

In [ ]:
# by using lamda we can create a function 

In [13]:
N,n = 20,5
def f(i):
    return(i% n == 0)*1
comb = np.fromfunction(f,(N,), dtype=int)
comb

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [14]:
a = np.array(((1,0,2),(1,0,2)))
a.shape

(2, 3)

In [ ]:
# 2rows and 3 columns 

In [15]:
a.ndim 

2

In [16]:
#  it is saying a have 2 dimensions


In [17]:
#  if we get (2,3,4) 2 is a depth , length , width

In [18]:
a.dtype #we get an which data type

dtype('int32')

In [19]:
a.data # we get a memory location

In [20]:
a.itemsize # we get size in bytes

4

In [22]:
x = np.linspace(1,10,10)
x**3

array([   1.,    8.,   27.,   64.,  125.,  216.,  343.,  512.,  729.,
       1000.])

In [23]:
x**2

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [24]:
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
x-1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:
np.sqrt(x-1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [28]:
np.sqrt(x**2)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
y = np.exp(-np.linspace(0,2,10))
np.sin(x-y)

array([ 0.        ,  0.93177163,  0.70524811, -0.33818748, -0.99238341,
       -0.5748152 ,  0.43786052,  0.99788475,  0.55950734, -0.425837  ])

In [32]:
a= np.array(((1,2),(3,4)))


In [33]:
b=a

In [35]:
a*b

array([[ 1,  4],
       [ 9, 16]])

In [36]:
a@b

array([[ 7, 10],
       [15, 22]])

In [37]:
np.matmul(a,b)

array([[ 7, 10],
       [15, 22]])

In [38]:
a.dot(b)

array([[ 7, 10],
       [15, 22]])

In [40]:
np.dot(a,b)

array([[ 7, 10],
       [15, 22]])

In [41]:
0/0

ZeroDivisionError: division by zero

In [42]:
np.inf

inf

In [43]:
#  creating a magic square
#  its a square matrix of order n 
# n(n^2 +1)/2


In [46]:
N=5
msquare = np.zeros((N,N), dtype = int)

n=1 
i,j = 0, N//2

while n <= N**2:
    msquare[i,j] = n
    n += 1
    newi,newj = (i-1)%N, (j+1)%N
    if msquare[newi,newj]:
        i += 1
    else:
        i,j = newi,newj
msquare
        

array([[17, 24,  1,  8, 15],
       [23,  5,  7, 14, 16],
       [ 4,  6, 13, 20, 22],
       [10, 12, 19, 21,  3],
       [11, 18, 25,  2,  9]])

In [47]:
# sum of any row, any column , or diagonal elements we get 65


In [48]:
b = msquare.flatten()

In [49]:
b


array([17, 24,  1,  8, 15, 23,  5,  7, 14, 16,  4,  6, 13, 20, 22, 10, 12,
       19, 21,  3, 11, 18, 25,  2,  9])

In [50]:
b[5] = 7


In [51]:
b

array([17, 24,  1,  8, 15,  7,  5,  7, 14, 16,  4,  6, 13, 20, 22, 10, 12,
       19, 21,  3, 11, 18, 25,  2,  9])

In [52]:
c= msquare.ravel()

In [53]:
c

array([17, 24,  1,  8, 15, 23,  5,  7, 14, 16,  4,  6, 13, 20, 22, 10, 12,
       19, 21,  3, 11, 18, 25,  2,  9])

In [60]:
a = np.linspace(1,16,16)

In [61]:
a


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16.])

In [62]:
a.resize(2,2,4)
a

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

In [63]:
a.shape

(2, 2, 4)

In [64]:
a.reshape(2,4,2)

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.],
        [13., 14.],
        [15., 16.]]])

In [66]:
b[0,3,1] = 7
b

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [81]:
# np.set_printoption(suppress=True)
x = np.arange(-15,15,0.1)


In [82]:
np.arange?

In [77]:
x.shape

(300,)

In [78]:
x

array([-1.50000000e+01, -1.49000000e+01, -1.48000000e+01, -1.47000000e+01,
       -1.46000000e+01, -1.45000000e+01, -1.44000000e+01, -1.43000000e+01,
       -1.42000000e+01, -1.41000000e+01, -1.40000000e+01, -1.39000000e+01,
       -1.38000000e+01, -1.37000000e+01, -1.36000000e+01, -1.35000000e+01,
       -1.34000000e+01, -1.33000000e+01, -1.32000000e+01, -1.31000000e+01,
       -1.30000000e+01, -1.29000000e+01, -1.28000000e+01, -1.27000000e+01,
       -1.26000000e+01, -1.25000000e+01, -1.24000000e+01, -1.23000000e+01,
       -1.22000000e+01, -1.21000000e+01, -1.20000000e+01, -1.19000000e+01,
       -1.18000000e+01, -1.17000000e+01, -1.16000000e+01, -1.15000000e+01,
       -1.14000000e+01, -1.13000000e+01, -1.12000000e+01, -1.11000000e+01,
       -1.10000000e+01, -1.09000000e+01, -1.08000000e+01, -1.07000000e+01,
       -1.06000000e+01, -1.05000000e+01, -1.04000000e+01, -1.03000000e+01,
       -1.02000000e+01, -1.01000000e+01, -1.00000000e+01, -9.90000000e+00,
       -9.80000000e+00, -

In [83]:
x

array([-15. , -14.9, -14.8, -14.7, -14.6, -14.5, -14.4, -14.3, -14.2,
       -14.1, -14. , -13.9, -13.8, -13.7, -13.6, -13.5, -13.4, -13.3,
       -13.2, -13.1, -13. , -12.9, -12.8, -12.7, -12.6, -12.5, -12.4,
       -12.3, -12.2, -12.1, -12. , -11.9, -11.8, -11.7, -11.6, -11.5,
       -11.4, -11.3, -11.2, -11.1, -11. , -10.9, -10.8, -10.7, -10.6,
       -10.5, -10.4, -10.3, -10.2, -10.1, -10. ,  -9.9,  -9.8,  -9.7,
        -9.6,  -9.5,  -9.4,  -9.3,  -9.2,  -9.1,  -9. ,  -8.9,  -8.8,
        -8.7,  -8.6,  -8.5,  -8.4,  -8.3,  -8.2,  -8.1,  -8. ,  -7.9,
        -7.8,  -7.7,  -7.6,  -7.5,  -7.4,  -7.3,  -7.2,  -7.1,  -7. ,
        -6.9,  -6.8,  -6.7,  -6.6,  -6.5,  -6.4,  -6.3,  -6.2,  -6.1,
        -6. ,  -5.9,  -5.8,  -5.7,  -5.6,  -5.5,  -5.4,  -5.3,  -5.2,
        -5.1,  -5. ,  -4.9,  -4.8,  -4.7,  -4.6,  -4.5,  -4.4,  -4.3,
        -4.2,  -4.1,  -4. ,  -3.9,  -3.8,  -3.7,  -3.6,  -3.5,  -3.4,
        -3.3,  -3.2,  -3.1,  -3. ,  -2.9,  -2.8,  -2.7,  -2.6,  -2.5,
        -2.4,  -2.3,

In [84]:
a

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

In [89]:
a[0,1,3] = 7

In [90]:
a


array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  7.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

In [93]:
z = np.arange(1,10,2)

In [94]:
z

array([1, 3, 5, 7, 9])

In [95]:
print(a)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  7.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


In [97]:
a.transpose()

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 7., 16.]]])

In [98]:
print(a)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  7.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


In [99]:
a.shape


(2, 2, 4)

In [100]:
a.transpose().shape

(4, 2, 2)

In [102]:
a.T

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 7., 16.]]])

In [110]:
j= np.array((0,0,0,0))
k= np.array((1,1,1,1))
l= np.array((2,2,2,2))
m=np.dstack((j,k,l))


In [111]:
m

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [112]:
n=np.vstack((j,k,l))

In [113]:
n

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [114]:
o=np.hstack((j,k,l))

In [115]:
o

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

In [117]:
np.hsplit?

In [127]:
 l=np.arange(16).reshape(4,4)

In [128]:
l


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [122]:
l.shape(4,4)

TypeError: 'tuple' object is not callable

In [125]:
np.hsplit?

In [126]:
l = np.reshape(4,4)

ValueError: cannot reshape array of size 1 into shape (4,)

In [131]:
a = np.linspace(1,20,10)
a

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [132]:
a[0:10:2]

array([ 1.        ,  5.22222222,  9.44444444, 13.66666667, 17.88888889])

In [133]:
a[0::3]

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [134]:
a[3::-2]

array([7.33333333, 3.11111111])

In [145]:
a = np.linspace(1,20,10).reshape(2,5)
a

array([[ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444],
       [11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ]])

In [140]:
a[0,0]

1.0

In [141]:
a[:0]

array([], shape=(0, 5), dtype=float64)

In [142]:
a[:,1]

array([ 3.11111111, 13.66666667])

In [149]:
a = np.arange(0,20,1).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [150]:
b = a[::, np.newaxis]

In [151]:
b

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19]]])

In [152]:
b.shape

(4, 1, 5)